#!/usr/bin/env bash
# Generates benign TLS traffic against this lab's classical and PQC
# servers, for benign_classical / benign_hybrid_pqc training data.
# Safe: only ever targets this repo's own docker-compose lab on
# localhost; accepts no external target.
set -euo pipefail

CLASSICAL_PORT="${TLS_CLASSICAL_PORT:-8443}"
PQC_PORT="${PQC_TLS_PORT:-8444}"
CONNECTIONS_PER_EXPERIMENT="${BENIGN_CONNECTION_COUNT:-60}"
INTERVAL_SECONDS="${BENIGN_INTERVAL_SECONDS:-1}"
LABELS_DIR="data/labels"

mkdir -p "$LABELS_DIR"

iso_ts() {
  date -u -d "@${1}" +"%Y-%m-%dT%H:%M:%SZ"
}

run_experiment() {
  local port="$1" servername="$2"
  local count=0 start_epoch end_epoch

  start_epoch=$(date +%s)
  for ((i = 1; i <= CONNECTIONS_PER_EXPERIMENT; i++)); do
    echo | openssl s_client -connect "localhost:${port}" -servername "$servername" -tls1_3 >/dev/null 2>&1 || true
    count=$((count + 1))
    sleep "$INTERVAL_SECONDS"
  done
  end_epoch=$(date +%s)

  echo "${start_epoch}|${end_epoch}|${count}"
}

write_manifest() {
  local experiment_id="$1" label="$2" label_name="$3" port="$4"
  local start_epoch="$5" end_epoch="$6" count="$7"
  local start_ts end_ts

  start_ts=$(iso_ts $((start_epoch - 2)))
  end_ts=$(iso_ts $((end_epoch + 2)))

  cat > "${LABELS_DIR}/${experiment_id}.json" << EOF
{
  "experiment_id": "${experiment_id}",
  "expected_label": ${label},
  "label_name": "${label_name}",
  "description": "Benign TLS handshakes generated by generate_benign_traffic.sh",
  "target_host": "localhost",
  "target_ports": [${port}],
  "start_time": "${start_ts}",
  "end_time": "${end_ts}",
  "connection_count": ${count},
  "generator_script": "generate_benign_traffic.sh"
}
EOF
  echo "[benign] wrote ${LABELS_DIR}/${experiment_id}.json"
}

echo "[benign] generating ${CONNECTIONS_PER_EXPERIMENT} classical connections against port ${CLASSICAL_PORT}"
IFS='|' read -r start_epoch end_epoch count <<< "$(run_experiment "$CLASSICAL_PORT" "classical-api.lab.local")"
write_manifest "exp-001-benign-classical" 0 "benign_classical" "$CLASSICAL_PORT" "$start_epoch" "$end_epoch" "$count"

echo "[benign] generating ${CONNECTIONS_PER_EXPERIMENT} PQC connections against port ${PQC_PORT}"
IFS='|' read -r start_epoch end_epoch count <<< "$(run_experiment "$PQC_PORT" "pqc-api.lab.local")"
write_manifest "exp-002-benign-hybrid-pqc" 1 "benign_hybrid_pqc" "$PQC_PORT" "$start_epoch" "$end_epoch" "$count"

echo "[benign] done"
