#!/usr/bin/env bash
# =============================================================================
# SAFETY: This script generates a BOUNDED burst of rapid TLS connections
# against the project's OWN isolated Docker Compose lab, for the sole
# purpose of producing labeled handshake_exhaustion training data.
#
#   - Targets are HARDCODED to localhost:8443 / localhost:8444 (this lab's
#     own containers). No external host or IP is ever accepted as a
#     parameter.
#   - The total connection count is capped by MAX_CONNECTIONS below -
#     there is no infinite-loop / continuous-flood mode.
#   - Do NOT modify this script to target any host other than this lab.
#   - Do NOT run this against any system you do not own and control.
# =============================================================================
set -euo pipefail

readonly CLASSICAL_PORT="${TLS_CLASSICAL_PORT:-8443}"
readonly PQC_PORT="${PQC_TLS_PORT:-8444}"
readonly MAX_CONNECTIONS="${EXHAUSTION_CONNECTION_COUNT:-200}"
readonly CONCURRENCY="${EXHAUSTION_CONCURRENCY:-20}"
LABELS_DIR="data/labels"

mkdir -p "$LABELS_DIR"

iso_ts() {
  date -u -d "@${1}" +"%Y-%m-%dT%H:%M:%SZ"
}

fire_one() {
  local port="$1" servername="$2"
  echo | openssl s_client -connect "localhost:${port}" -servername "$servername" -tls1_3 >/dev/null 2>&1 || true
}
export -f fire_one

echo "[exhaustion] firing ${MAX_CONNECTIONS} bounded rapid connections (concurrency=${CONCURRENCY})"
echo "[exhaustion] targets: localhost:${CLASSICAL_PORT}, localhost:${PQC_PORT} (this lab only)"

start_epoch=$(date +%s)

for ((i = 1; i <= MAX_CONNECTIONS; i++)); do
  if (( i % 2 == 0 )); then
    echo "${PQC_PORT}|pqc-api.lab.local"
  else
    echo "${CLASSICAL_PORT}|classical-api.lab.local"
  fi
done | xargs -P "$CONCURRENCY" -I{} bash -c '
  IFS="|" read -r port servername <<< "{}"
  fire_one "$port" "$servername"
'

end_epoch=$(date +%s)
start_ts=$(iso_ts $((start_epoch - 2)))
end_ts=$(iso_ts $((end_epoch + 2)))

cat > "${LABELS_DIR}/exp-004-handshake-exhaustion.json" << EOF
{
  "experiment_id": "exp-004-handshake-exhaustion",
  "expected_label": 3,
  "label_name": "handshake_exhaustion",
  "description": "Bounded burst of ${MAX_CONNECTIONS} rapid, concurrent TLS connections alternating between both lab servers, generated by generate_exhaustion_cases.sh",
  "target_host": "localhost",
  "target_ports": [${CLASSICAL_PORT}, ${PQC_PORT}],
  "start_time": "${start_ts}",
  "end_time": "${end_ts}",
  "connection_count": ${MAX_CONNECTIONS},
  "generator_script": "generate_exhaustion_cases.sh"
}
EOF

echo "[exhaustion] wrote ${LABELS_DIR}/exp-004-handshake-exhaustion.json"
