#!/usr/bin/env bash
# Forces classical-only TLS negotiation (-groups x25519) against the
# PQC-required lab server, producing downgrade_violation training data.
# Safe: only ever targets this repo's own docker-compose lab on
# localhost.
set -euo pipefail

PQC_PORT="${PQC_TLS_PORT:-8444}"
CONNECTION_COUNT="${DOWNGRADE_CONNECTION_COUNT:-30}"
INTERVAL_SECONDS="${DOWNGRADE_INTERVAL_SECONDS:-1}"
LABELS_DIR="data/labels"

mkdir -p "$LABELS_DIR"

iso_ts() {
  date -u -d "@${1}" +"%Y-%m-%dT%H:%M:%SZ"
}

echo "[downgrade] forcing classical group (x25519) against PQC-required port ${PQC_PORT}"

start_epoch=$(date +%s)
count=0
for ((i = 1; i <= CONNECTION_COUNT; i++)); do
  echo | openssl s_client -connect "localhost:${PQC_PORT}" -servername pqc-api.lab.local -tls1_3 -groups x25519 >/dev/null 2>&1 || true
  count=$((count + 1))
  sleep "$INTERVAL_SECONDS"
done
end_epoch=$(date +%s)

start_ts=$(iso_ts $((start_epoch - 2)))
end_ts=$(iso_ts $((end_epoch + 2)))

cat > "${LABELS_DIR}/exp-003-downgrade-violation.json" << EOF
{
  "experiment_id": "exp-003-downgrade-violation",
  "expected_label": 2,
  "label_name": "downgrade_violation",
  "description": "TLS handshakes forced to negotiate a classical-only group (x25519) against the PQC-required tls-pqc service, generated by generate_downgrade_cases.sh",
  "target_host": "localhost",
  "target_ports": [${PQC_PORT}],
  "start_time": "${start_ts}",
  "end_time": "${end_ts}",
  "connection_count": ${count},
  "generator_script": "generate_downgrade_cases.sh"
}
EOF

echo "[downgrade] wrote ${LABELS_DIR}/exp-003-downgrade-violation.json"
echo "[downgrade] NOTE: if tls-pqc is currently running its classical-fallback stub"
echo "[downgrade] (default lab config), this traffic is wire-identical to benign"
echo "[downgrade] PQC traffic that also fell back - see KNOWN_LIMITATIONS.md"
