#!/usr/bin/env bash
# Sends deliberately malformed TLS byte sequences (truncated ClientHello,
# invalid extension length, garbage bytes) against this lab's own
# containers, for generating malformed_handshake training data.
#
# KNOWN LIMITATION: Zeek's SSL analyzer may not log these connections in
# ssl.log at all, since the payloads are not valid TLS. See
# KNOWN_LIMITATIONS.md and scripts/send_malformed_tls.py.
set -euo pipefail

CLASSICAL_PORT="${TLS_CLASSICAL_PORT:-8443}"
PQC_PORT="${PQC_TLS_PORT:-8444}"
CASES=(truncated bad-extension garbage)
COUNT_PER_CASE="${MALFORMED_COUNT_PER_CASE:-10}"
LABELS_DIR="data/labels"

mkdir -p "$LABELS_DIR"

iso_ts() {
  date -u -d "@${1}" +"%Y-%m-%dT%H:%M:%SZ"
}

echo "[malformed] sending malformed TLS payloads against ports ${CLASSICAL_PORT}, ${PQC_PORT}"

start_epoch=$(date +%s)
total_count=0
for port in "$CLASSICAL_PORT" "$PQC_PORT"; do
  for case in "${CASES[@]}"; do
    echo "[malformed] case=${case} port=${port} count=${COUNT_PER_CASE}"
    python -m scripts.send_malformed_tls --host localhost --port "$port" --case "$case" --count "$COUNT_PER_CASE"
    total_count=$((total_count + COUNT_PER_CASE))
  done
done
end_epoch=$(date +%s)

start_ts=$(iso_ts $((start_epoch - 2)))
end_ts=$(iso_ts $((end_epoch + 2)))

cat > "${LABELS_DIR}/exp-005-malformed-handshake.json" << EOF
{
  "experiment_id": "exp-005-malformed-handshake",
  "expected_label": 4,
  "label_name": "malformed_handshake",
  "description": "Deliberately malformed TLS byte sequences (truncated ClientHello, invalid extension length, garbage bytes) sent against this lab's servers, generated by generate_malformed_cases.sh. NOTE: many of these connections may not appear in ssl.log at all - see KNOWN_LIMITATIONS.md.",
  "target_host": "localhost",
  "target_ports": [${CLASSICAL_PORT}, ${PQC_PORT}],
  "start_time": "${start_ts}",
  "end_time": "${end_ts}",
  "connection_count": ${total_count},
  "generator_script": "generate_malformed_cases.sh"
}
EOF

echo "[malformed] wrote ${LABELS_DIR}/exp-005-malformed-handshake.json"
